project:
  type: website
  pre-render: _common.R
  output-dir: _site

website:
  title: "Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cardena.qmd
        text: Cardeña

format:
  dashboard:
    theme: journal
