project:
  type: website
  pre-render: _common.R
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "TREAD"
  navbar:
    background: primary
    left:
      - text: Flights
        menu:
          - href: cordoba-flights.qmd
            text: "Raso del Conejo"
          - href: cardena-flights.qmd
            text: "Vegueta"
          - href: segovia-flights.qmd
            text: "Valsaín"
          - href: madrid-flights.qmd
            text: "Valdemaqueda"
          - href: pontedesor-flights.qmd
            text: "Herdade de João Galego"
          - href: nazare-flights.qmd
            text: "Mata do Valado de Frades"
      - text: Sensors
        menu:
          - href: cardena-sensors.qmd
            text: "Cardeña"
      - href: team.qmd
        text: Research Team

format:
  dashboard:
    theme: journal
    css: styles.css
